### ISSUE TITLE
대중적인 맥주 데이터 추가

### ISSUE THREAD

**Issue by hy57in** [depromeet/sulsul-BE#219]
카스, 테라, 이슬톡톡 등

**Comment by zeze1004** [comment]
제안 감사합니다! 운영 디비 추가했습니다

**Comment by Ting-Kim** [comment]
추가된 맥주 : 테라, 이슬톡톡, 지비에츠, 블루걸, 서뉴잉글랜드쉔디, 제주 거몽 에일, 하이트, 하이트 제로, 맥스

더 추가할 맥주가 있다면 추가로 issue 작성해주세요 👍
