### ISSUE TITLE
티켓 수정 안되고 새로 생성됨

### ISSUE THREAD

**Issue by zeze1004** [depromeet/sulsul-BE#222]
@효진님 제보
티켓 수정하면 덮어씌워지는게 아니라 새로운 티켓이 발급됨
## 🔗 참고자료

![image](https://user-images.githubusercontent.com/44468282/175986783-f661e173-efb0-47c9-b429-e01ae3de509f.png)

**Comment by RyooChan** [comment]
@hy57in 혹시 이부분 더이상 이슈 없으시면 close하겠습니다!

**Comment by RyooChan** [comment]
더이상 이슈 없다고 판단되어 close합니다!
