### ISSUE TITLE
DB 설계(ERD)

### ISSUE THREAD

**Issue by Ting-Kim** [depromeet/sulsul-BE#9]
## 📍 작업 사항

- ERD Cloud 를 이용한 DB 설계
  > 일단 최대한 정규화를 진행했습니다. 정규화를 해놓고 비정규화를 논의해봐도 좋을 것 같아요.
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/59888684/165101736-f02988eb-e877-4691-abcd-be97ff8c0d66.png">

- 모델 구현 #10 

## 👪 작업에 참여한 인원

- @minsoozz
- @RyooChan

## 🔗 참고자료

- [4/10 백엔드 회의 자료](https://www.notion.so/depromeet/899f496d22924de5b84fe7e6f8a4fc5f)
- [8조 SulSul Figma](https://www.figma.com/file/cWQqi0du7p8oLxUco6w98l/%EB%94%94%ED%94%84%EB%A7%8C-11%EA%B8%B0-8%EC%A1%B0?node-id=8%3A48)

**Comment by RyooChan** [comment]
늦게 확인해서 죄송합니다! 같이 고민했어야 했는데 저는 완전 아무것도 안했네요ㅜㅜ.... 추가로 논의해보고 싶은 내용들은
* MEMBER의 각 OAuth2 방식에 관하여 회원id를 FK로 받아 일대다 테이블 생성 여부
* BEER_FLAVOR의 좋아요 수를 받아오는 테이블 생성 여부
    * MEMBER와 일대다로 연결된 HEART테이블이 존재하여, 좋아요/좋아요취소 여부를 추가로 받는 것이 있으면 좋을 듯 합니다.
* 추가로 혹시 FLAVOR테이블이 따로 있는 이유는 태그를 따로 분리하여 적용하기 위해서일까요??

테이블 ERD설계 고생하셨습니다!!

**Comment by Ting-Kim** [comment]
- MEMBER의 각 OAuth2 방식에 관하여 회원id를 FK로 받아 일대다 테이블 생성 여부
  -> 저도 이전 프로젝트에서 이렇게 구현했는데, 또 다른 방법이 있을까요? ㅎㅎ
- BEER_FLAVOR의 좋아요 수를 받아오는 테이블 생성 여부 
  - MEMBER와 일대다로 연결된 HEART테이블이 존재하여, 좋아요/좋아요취소 여부를 추가로 받는 것이 있으면 좋을 듯 합니다.
    -> 좋은 포인트 감사합니다! 놓쳤군요! 다만 테이블 네이밍은 좀 고민이 되네요. 저는 `member-item` 사이에 좋아요를 이전에 `member_item` 관계로 구현했었는데, 좋아요는 어디든지 발생할 수 있기 때문에 둘의 관계가 조금 드러났으면 좋겠다는 생각도 듭니다 ㅎㅎ
- 추가로 혹시 FLAVOR테이블이 따로 있는 이유는 태그를 따로 분리하여 적용하기 위해서일까요??
  -> **Figma**에 보시면 맛을 표현한 키워드들을 초기에 저희가 정해놓고 사용하는데요, 단순히 `ENUM`을 사용할 순 없을까 하다가 이후에 맛 키워드가 추가되면 코드의 수정이 발생하기 때문에 우선은 DB 테이블로 넣어버렸습니다. 사실 이러한 부분들을 우선 `RDBMS`로 모두 표현한 후, 팀원들과 논의하여 비정규화나 `In-memory DB` 등을 사용하거나 해서 효율성을 높이고 싶은 마음이 있기 때문에, 어떠한 의견이든 너무 좋습니다!

**Comment by RyooChan** [comment]
@Ting-Kim 
빠른 답변 감사합니다!! 저도 조금 더 고민해 봐야겠네요... 
다음번에 회의하면서 더 확인해보아요!ㅎㅎ

**Comment by minsoozz** [comment]
@Ting-Kim 맥주 종류를 맥주에 포함 시키면 검색 구현에 있어서 조금 편할 것 같아요!

**Comment by Ting-Kim** [comment]
@minsoozz 오 검색이면 맞네요! 맥주 종류를 ENUM으로 관리해야 할까요? ㅎㅎ
